# Generated by Django 4.2 on 2023-05-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_internal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
