# Generated by Django 4.2 on 2023-06-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='path',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
