# Generated by Django 4.2 on 2023-07-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images')),
                ('article_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
