# Generated by Django 4.2 on 2023-07-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articleimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleimages',
            old_name='image',
            new_name='location',
        ),
    ]
