# Generated by Django 4.2 on 2023-07-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_rename_image_articleimages_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
