# Generated by Django 4.2 on 2023-04-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='active_deployment',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='data_model',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='purchase_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='starred_date',
            field=models.DateTimeField(null=True),
        ),
    ]
