# Generated by Django 4.2 on 2023-04-28 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_instrument_active_deployment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrument',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
