# Generated by Django 4.2 on 2023-04-29 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_instrument_user_alter_instrument_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='notes',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('notes', models.TextField(max_length=5000, null=True)),
                ('deployment_start_date', models.DateTimeField(null=True)),
                ('deployment_end_date', models.DateTimeField(null=True)),
                ('private', models.BooleanField(null=True)),
                ('starred', models.BooleanField(default=False)),
                ('starred_date', models.DateTimeField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('collaborators', models.ManyToManyField(to='api.collaborators')),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instrument')),
                ('tags', models.ManyToManyField(to='api.deploymenttags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
