# Generated by Django 4.2 on 2023-04-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_collaborators_deploymenttags_instrument_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='instrument_id',
        ),
        migrations.AddField(
            model_name='deployment',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.instrument'),
        ),
    ]
