# Generated by Django 4.2 on 2023-04-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_deployment_collaborators_delete_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='private',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='starred',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
