# Generated by Django 4.2 on 2023-04-29 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_alter_deployment_location_alter_deployment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.deploymenttags'),
        ),
    ]
