# Generated by Django 4.2 on 2023-04-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_instrument_name_alter_instrument_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='notes',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
