# Generated by Django 4.2 on 2023-05-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_instrument_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='notes',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
