# Generated by Django 4.2 on 2023-05-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_deployment_description_alter_deployment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='general',
            field=models.JSONField(null=True),
        ),
    ]
