# Generated by Django 4.2 on 2023-05-19 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_instrument_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='instrument',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
