# Generated by Django 4.2 on 2023-05-19 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_simb3'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIMB3Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('deployment_description', models.TextField(blank=True, max_length=2000, null=True)),
                ('deployment_notes', models.TextField(blank=True, max_length=5000, null=True)),
                ('deployment_start_date', models.DateTimeField(null=True)),
                ('deployment_end_date', models.DateTimeField(null=True)),
                ('private', models.BooleanField(default=True, null=True)),
                ('starred', models.BooleanField(default=False, null=True)),
                ('starred_date', models.DateTimeField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.simb3')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Deployment',
        ),
        migrations.DeleteModel(
            name='DeploymentTags',
        ),
    ]
