# Generated by Django 4.2 on 2023-05-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_simb3deployment_delete_deployment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='simb3',
            name='version',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='simb3',
            name='transmission_interval',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AddField(
            model_name='simb3deployment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.deploymenttags'),
        ),
    ]
