# Generated by Django 4.2 on 2023-05-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_deploymenttags_simb3_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simb3',
            name='sensor_suite',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='simb3deployment',
            name='deployment_ice_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simb3deployment',
            name='deployment_snow_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simb3deployment',
            name='ending_row',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='simb3deployment',
            name='mb_plot_parameters',
            field=models.CharField(blank=True, default='0.5,-0.5,0,0,-3,0', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='simb3deployment',
            name='starting_row',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simb3deployment',
            name='deployment_notes',
            field=models.TextField(blank=True),
        ),
    ]
