# Generated by Django 4.2 on 2023-05-19 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0020_rename_data_model_simb3_date_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='field_type',
        ),
        migrations.AddField(
            model_name='datamodel',
            name='name',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=32)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datamodel')),
            ],
        ),
    ]
