# Generated by Django 4.2 on 2023-05-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_simb3data_remove_simb3_date_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simb3deployment',
            name='data',
        ),
    ]
