# Generated by Django 4.2 on 2023-05-19 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_simb3deployment_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='simb3data',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.simb3deployment'),
        ),
    ]
