# Generated by Django 4.2 on 2023-05-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_simb3deployment_deployment_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simb3data',
            name='deployment',
        ),
        migrations.RemoveField(
            model_name='simb3deployment',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='simb3deployment',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='simb3deployment',
            name='tags',
        ),
        migrations.DeleteModel(
            name='SIMB3',
        ),
        migrations.DeleteModel(
            name='SIMB3Data',
        ),
        migrations.DeleteModel(
            name='SIMB3Deployment',
        ),
    ]
