# Generated by Django 4.2 on 2023-05-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_instrument_deployment_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='user',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Deployment',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
