# Generated by Django 4.2 on 2023-05-19 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0028_remove_deployment_collaborators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIMB3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('notes', models.TextField(blank=True, max_length=5000, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('imei', models.CharField(max_length=100, null=True)),
                ('version', models.IntegerField(blank=True, default=1)),
                ('sensor_suite', models.IntegerField(blank=True, default=1)),
                ('transmission_interval', models.IntegerField(blank=True, default=4)),
                ('build_date', models.DateField(blank=True, null=True)),
                ('fetch_data', models.BooleanField(default=True)),
                ('decode', models.BooleanField(default=True)),
                ('post_to_database', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SIMB3Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('deployment_description', models.TextField(blank=True, max_length=2000, null=True)),
                ('deployment_notes', models.TextField(blank=True, max_length=5000, null=True)),
                ('deployment_start_date', models.DateTimeField(null=True)),
                ('deployment_end_date', models.DateTimeField(null=True)),
                ('private', models.BooleanField(default=True, null=True)),
                ('starred', models.BooleanField(default=False, null=True)),
                ('starred_date', models.DateTimeField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('deployment_ice_thickness', models.FloatField(blank=True, null=True)),
                ('deployment_snow_thickness', models.FloatField(blank=True, null=True)),
                ('starting_row', models.IntegerField(default=0)),
                ('ending_row', models.IntegerField(blank=True, default=None, null=True)),
                ('mb_plot_parameters', models.CharField(blank=True, default='0.5,-0.5,0,0,-3,0', max_length=50, null=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.simb3')),
                ('tags', models.ManyToManyField(blank=True, to='api.deploymenttags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SIMB3Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.simb3deployment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
