# Generated by Django 4.2 on 2023-05-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_simb3_simb3deployment_simb3data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='table',
        ),
        migrations.RemoveField(
            model_name='simb3',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='simb3data',
            name='deployment',
        ),
        migrations.RemoveField(
            model_name='simb3deployment',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='simb3deployment',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='simb3deployment',
            name='tags',
        ),
        migrations.DeleteModel(
            name='DataModel',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='SIMB3',
        ),
        migrations.DeleteModel(
            name='SIMB3Data',
        ),
        migrations.DeleteModel(
            name='SIMB3Deployment',
        ),
    ]
