# Generated by Django 4.2 on 2024-02-14 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instruments', '0045_alter_deployment_slug'),
        ('stats', '0002_alter_deploymentdownload_deployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentdownload',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deploymentdownload',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.deployment'),
        ),
        migrations.AlterField(
            model_name='deploymentdownload',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
