# Generated by Django 4.2 on 2023-05-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_instrument_imei_instrument_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
