# Generated by Django 4.2 on 2023-05-21 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_instrument_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='Instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployment_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployment_start_date',
            field=models.DateField(null=True),
        ),
    ]
