# Generated by Django 4.2 on 2023-05-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_deployment_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
