# Generated by Django 4.2 on 2023-05-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0007_alter_deployment_data_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='deployment_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='starred_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
