# Generated by Django 4.2 on 2023-05-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0008_alter_deployment_deployment_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='imei',
            new_name='serial_number',
        ),
    ]
