# Generated by Django 4.2 on 2023-05-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0010_alter_instrument_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='type',
            new_name='instrument_class',
        ),
    ]
