# Generated by Django 4.2 on 2023-05-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0011_rename_type_instrument_instrument_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='instrument_class',
        ),
        migrations.DeleteModel(
            name='AvailableInstruments',
        ),
    ]
