# Generated by Django 4.2 on 2023-05-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0012_remove_instrument_instrument_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
