# Generated by Django 4.2 on 2023-05-21 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0014_alter_deployment_deployment_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='Instrument',
            new_name='instrument',
        ),
    ]
