# Generated by Django 4.2 on 2023-05-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0015_rename_instrument_deployment_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='private',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
