# Generated by Django 4.2 on 2023-05-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0016_alter_deployment_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deployment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
