# Generated by Django 4.2 on 2023-06-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0018_alter_deployment_deployment_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
