# Generated by Django 4.2 on 2023-06-11 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0019_deployment_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='slug',
            new_name='path',
        ),
    ]
