# Generated by Django 4.2 on 2023-06-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0020_rename_slug_deployment_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/instruments/avatars'),
        ),
    ]
