# Generated by Django 4.2 on 2023-06-29 14:40

from django.db import migrations, models
import instruments.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0021_alter_instrument_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=instruments.base_models.BaseInstrument.get_image_upload_path),
        ),
    ]
