# Generated by Django 4.2 on 2023-06-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0022_alter_instrument_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/instruments/avatars'),
        ),
    ]
