# Generated by Django 4.2 on 2023-07-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0024_deployment_slug_alter_instrument_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('fields', models.JSONField(blank=True, default="[{'name': 'test_field', 'pretty_name': 'Test Field', 'unit': 'C', 'unique': 'true'}]", null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
