# Generated by Django 4.2 on 2023-07-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0025_datamodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataModel',
            new_name='instrumentSensorPackage',
        ),
        migrations.AddField(
            model_name='instrument',
            name='sensor_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumentsensorpackage'),
        ),
    ]
