# Generated by Django 4.2 on 2023-07-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0027_instrumentsensorpackage_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentsensorpackage',
            options={'verbose_name': 'Instrument Sensor Package'},
        ),
        migrations.AlterField(
            model_name='instrumentsensorpackage',
            name='fields',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
