# Generated by Django 4.2 on 2023-07-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0028_alter_instrumentsensorpackage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentsensorpackage',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
