# Generated by Django 4.2 on 2023-07-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0029_instrumentsensorpackage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='rows_from_end',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='rows_from_start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
