# Generated by Django 4.2 on 2023-07-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0030_deployment_rows_from_end_deployment_rows_from_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='instruments/avatars'),
        ),
    ]
