# Generated by Django 4.2 on 2023-08-05 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0031_alter_instrument_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='internal',
        ),
    ]
