# Generated by Django 4.2 on 2023-08-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0032_remove_instrument_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='searchable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
