# Generated by Django 4.2 on 2023-08-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0034_realtimedecoding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealTimeDecoding',
        ),
    ]
