# Generated by Django 4.2 on 2023-08-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0035_delete_realtimedecoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='is_simb3',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
