# Generated by Django 4.2 on 2023-08-12 15:55

from django.db import migrations, models
import django.db.models.deletion
import instruments.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0036_instrument_is_simb3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=instruments.base_models.generate_instrument_avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='sensor_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.instrumentsensorpackage'),
        ),
    ]
