# Generated by Django 4.2 on 2023-08-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0038_instrument_sensors_instrument_unique_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='starred',
            new_name='web_page_enabled',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='starred_date',
        ),
        migrations.AddField(
            model_name='deployment',
            name='unique_index',
            field=models.CharField(blank=True, null=True),
        ),
    ]
