# Generated by Django 4.2 on 2023-12-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0039_rename_starred_deployment_web_page_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentsensorpackage',
            name='latitude_database_field',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrumentsensorpackage',
            name='longitude_database_field',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrumentsensorpackage',
            name='template',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentsensorpackage',
            name='template_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instrumentsensorpackage',
            name='time_stamp_database_field',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrumentsensorpackage',
            name='time_stamp_format',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
