# Generated by Django 4.2 on 2023-12-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0040_instrumentsensorpackage_latitude_database_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentsensorpackage',
            name='name',
        ),
    ]
