# Generated by Django 4.2 on 2024-01-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0041_remove_instrumentsensorpackage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentsensorpackage',
            name='latitude_database_field',
        ),
        migrations.RemoveField(
            model_name='instrumentsensorpackage',
            name='longitude_database_field',
        ),
        migrations.AddField(
            model_name='instrumentsensorpackage',
            name='latitude_field',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='instrumentsensorpackage',
            name='longitude_field',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentsensorpackage',
            name='time_stamp_database_field',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
