# Generated by Django 4.2 on 2024-01-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0042_remove_instrumentsensorpackage_latitude_database_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentsensorpackage',
            name='time_stamp_database_field',
        ),
        migrations.AddField(
            model_name='instrumentsensorpackage',
            name='time_stamp_field',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentsensorpackage',
            name='fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentsensorpackage',
            name='latitude_field',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentsensorpackage',
            name='longitude_field',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
