# Generated by Django 4.2 on 2024-02-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0043_remove_instrumentsensorpackage_time_stamp_database_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='sensors',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
