# Generated by Django 4.2 on 2024-02-19 12:52

from django.db import migrations, models
import instruments.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0045_alter_deployment_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FileField(blank=True, null=True, upload_to=instruments.base_models)),
                ('type', models.CharField(blank=True, null=True)),
                ('size', models.CharField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='deployment',
            name='media',
            field=models.ManyToManyField(to='instruments.documentmedia'),
        ),
    ]
