# Generated by Django 4.2 on 2024-02-19 13:34

from django.db import migrations, models
import django.db.models.deletion
import instruments.models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0046_documentmedia_deployment_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FileField(blank=True, null=True, upload_to=instruments.models.custom_filename)),
                ('type', models.CharField(blank=True, null=True)),
                ('size', models.CharField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='media',
        ),
        migrations.DeleteModel(
            name='DocumentMedia',
        ),
        migrations.AddField(
            model_name='deploymentmedia',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.deployment'),
        ),
    ]
