# Generated by Django 4.2 on 2024-02-19 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0047_deploymentmedia_remove_deployment_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentmedia',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
