# Generated by Django 4.2 on 2024-02-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0048_deploymentmedia_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentmedia',
            name='placeholder',
            field=models.TextField(blank=True, null=True),
        ),
    ]
