# Generated by Django 4.2 on 2024-02-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0049_deploymentmedia_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='database_parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
