# Generated by Django 4.2 on 2024-02-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0050_deployment_database_parameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploymentmedia',
            old_name='placeholder',
            new_name='description',
        ),
        migrations.AddField(
            model_name='deploymentmedia',
            name='private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
