# Generated by Django 4.2 on 2024-02-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0053_deploymentmedia_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='rows_from_end',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
