# Generated by Django 4.2 on 2024-03-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0056_instrument_build_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='build_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
