# Generated by Django 4.2 on 2024-03-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0057_alter_instrument_build_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
