# Generated by Django 4.2 on 2024-03-14 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0059_deployentinitialconditions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeployentInitialConditions',
            new_name='DeploymentInitialConditions',
        ),
    ]
