# Generated by Django 4.2 on 2023-08-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0035_delete_realtimedecoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeDecoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('decode_script_name', models.CharField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('deployment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instruments.deployment')),
            ],
            options={
                'verbose_name': 'Real-Time Data',
            },
        ),
    ]
