# Generated by Django 4.2 on 2023-08-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0035_delete_realtimedecoding'),
        ('real_time_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RealTimeDecoding',
            new_name='RealTimeData',
        ),
    ]
