# Generated by Django 4.2 on 2023-08-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_time_data', '0003_decodescript_alter_realtimedata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimedata',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
