# Generated by Django 4.2 on 2023-08-07 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0035_delete_realtimedecoding'),
        ('real_time_data', '0005_realtimedata_iridium_imei_realtimedata_iridium_sbd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimedata',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='realtimedata',
            name='decode_script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_time_data.decodescript'),
        ),
        migrations.AlterField(
            model_name='realtimedata',
            name='deployment',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.deployment'),
        ),
    ]
