# Generated by Django 4.2 on 2023-08-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_time_data', '0006_alter_realtimedata_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimedata',
            name='decoding',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
