# Generated by Django 4.2 on 2024-02-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_time_data', '0007_realtimedata_decoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='decodescript',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
