# Generated by Django 4.2 on 2024-02-09 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0044_alter_instrument_sensors'),
        ('real_time_data', '0008_decodescript_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBDData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbd_binary', models.BinaryField()),
                ('sbd_filename', models.CharField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('deployment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.deployment')),
            ],
        ),
    ]
