# Generated by Django 4.2 on 2024-02-09 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0044_alter_instrument_sensors'),
        ('real_time_data', '0010_alter_sbddata_sbd_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbddata',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.deployment'),
        ),
    ]
