# Generated by Django 4.2 on 2024-02-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_time_data', '0011_alter_sbddata_deployment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtimedata',
            old_name='decoding',
            new_name='dowloading',
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='resyncing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
