# Generated by Django 4.2 on 2024-02-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_time_data', '0012_rename_decoding_realtimedata_dowloading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtimedata',
            old_name='dowloading',
            new_name='downloading',
        ),
    ]
