# Generated by Django 4.2 on 2023-07-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived'), ('Internal', 'Internal')], default='Draft', max_length=30)),
                ('internal', models.BooleanField(default=False)),
                ('heading', models.CharField(blank=True, max_length=500, null=True)),
                ('featured', models.BooleanField(blank=True, default=0, null=True)),
                ('featured_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='documentation/images')),
                ('image_attribution', models.CharField(blank=True, max_length=500, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Documentation',
                'verbose_name_plural': 'Documentation',
            },
        ),
        migrations.CreateModel(
            name='Documentation_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_color', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Documentation Tag',
                'verbose_name_plural': 'Documentation Tags',
            },
        ),
        migrations.CreateModel(
            name='DocumentationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ImageField(blank=True, null=True, upload_to='documentation/images')),
                ('documentation_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
