# Generated by Django 4.2 on 2023-07-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
