# Generated by Django 4.2 on 2023-07-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_delete_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentation',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='Documentation_tags',
            new_name='Document_tags',
        ),
        migrations.RenameModel(
            old_name='DocumentationImages',
            new_name='DocumentImages',
        ),
    ]
