# Generated by Django 4.2 on 2023-07-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='document',
            name='featured_heading',
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
