# Generated by Django 4.2 on 2023-07-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0006_remove_document_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentimages',
            name='documentation_id',
        ),
        migrations.AddField(
            model_name='documentimages',
            name='size',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentimages',
            name='type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
