# Generated by Django 4.2 on 2023-07-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0009_alter_documentmedia_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmedia',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
