# Generated by Django 4.2 on 2023-07-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_updatesandchanges_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatesandchanges',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='updatesandchanges',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
