# Generated by Django 4.2 on 2023-07-20 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_customerquote_requester_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_text', models.CharField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.AlterField(
            model_name='customerquote',
            name='quote_file',
            field=models.FileField(blank=True, null=True, upload_to='quotes'),
        ),
    ]
