# Generated by Django 4.2 on 2023-07-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_banner_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
