# Generated by Django 4.2 on 2023-07-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_banner_banner_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurveys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_num', models.IntegerField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
