# Generated by Django 4.2 on 2023-07-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_contactus_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
