# Generated by Django 4.2 on 2024-02-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_alter_contactus_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_color',
            field=models.CharField(blank=True, null=True),
        ),
    ]
