# Generated by Django 4.2 on 2024-02-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_banner_banner_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='banner_color',
            new_name='banner_type',
        ),
    ]
