# Generated by Django 4.2 on 2024-02-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_rename_banner_color_banner_banner_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='banner_type',
            new_name='severity',
        ),
    ]
