# Generated by Django 4.2 on 2024-02-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_rename_banner_type_banner_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatesandchanges',
            name='published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
