# Generated by Django 4.2 on 2024-02-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_websitestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitestatus',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
