# Generated by Django 4.2 on 2024-02-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_websitestatus_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitestatus',
            name='severity',
        ),
    ]
