# Generated by Django 4.2 on 2024-02-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_remove_websitestatus_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
