# Generated by Django 4.2 on 2023-06-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='8db03bf0eabef3da235acc58a315514cbbaf6d1ed605898785233153a36b62c0', max_length=64, unique=True),
        ),
    ]
