# Generated by Django 4.2 on 2023-06-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_apikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='7v20QvwdBAkWClVZlpt51D1E2f6kJ7Dl', max_length=64, unique=True),
        ),
    ]
