# Generated by Django 4.2 on 2023-06-13 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_apikey_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='write_permissions',
            new_name='permissions',
        ),
    ]
