# Generated by Django 4.2 on 2023-08-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_write_permissions_apikey_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='permissions',
        ),
        migrations.AddField(
            model_name='apikey',
            name='read_only',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
