# Generated by Django 4.2 on 2023-06-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0018_alter_deployment_deployment_end_date_and_more'),
        ('user_profiles', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='watched_instruments',
            field=models.ManyToManyField(to='instruments.deployment'),
        ),
    ]
