# Generated by Django 4.2 on 2023-06-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0006_alter_userprofile_watched_instruments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='watched_instruments',
            new_name='watched_deployments',
        ),
    ]
