# Generated by Django 4.2 on 2023-07-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0008_rename_watched_deployments_userprofile_dashboard_deployments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars'),
        ),
    ]
