# Generated by Django 4.2 on 2023-07-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0009_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='robot',
            field=models.CharField(blank=True, default='Snickers', null=True),
        ),
    ]
