# Generated by Django 4.2 on 2023-08-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0012_rename_can_add_models_userprofile_beta_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_avatar',
            field=models.CharField(blank=True, null=True),
        ),
    ]
