# Generated by Django 4.2 on 2023-09-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0013_userprofile_google_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pinned', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pinned_deployments',
            field=models.ManyToManyField(blank=True, to='user_profiles.pinneddeployment'),
        ),
    ]
