# Generated by Django 4.2 on 2024-02-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
