# Generated by Django 4.2 on 2024-02-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
