# Generated by Django 4.2 on 2024-02-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_read_alter_notification_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
