# Generated by Django 4.2 on 2024-02-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_expiration_notification_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
